server:
  port: 8083

spring:
  application:
    name: emotion-service

  datasource:
    url: jdbc:postgresql://localhost:5433/mindcare_db?currentSchema=emotion_schema
    username: postgres_admin
    password: secretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: emotion_schema
    default-schema: emotion_schema

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
