/* Hallmark · pre-emit critique: P5 H5 E5 S5 R5 V5 */
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { Screen, SectionTitle } from '../../src/components/ui';
import { EmotionTrendChart } from '../../src/components/emotion-ui';
import { palette, radius, space, type } from '../../src/theme/tokens';
const days = [{ day: 'T2', score: 0, count: 1 }, { day: 'T3', score: 1, count: 1 }, { day: 'T4', score: 0, count: 1 }, { day: 'T5', score: 2, count: 1 }, { day: 'T6', score: null, count: 0 }, { day: 'T7', score: null, count: 0 }, { day: 'CN', score: null, count: 0 }];
export default function JourneyScreen() { return <Screen><ScrollView contentContainerStyle={styles.content}><Text style={styles.date}>7 NGÀY GẦN NHẤT</Text><Text style={styles.title}>Theo dõi sức khỏe của bạn</Text><Text style={styles.intro}>Nhìn vào các thay đổi theo thời gian, thay vì đánh giá một ngày đơn lẻ.</Text><View style={styles.rule} /><SectionTitle title="Cảm xúc" action="Xem lịch" /><View style={styles.chartCard}><EmotionTrendChart points={days} /><Text style={styles.caption}>4 check-in trong tuần · Mức cảm xúc ổn định trong những ngày có giấc ngủ đủ.</Text></View><View style={styles.rule} /><SectionTitle title="Xu hướng sức khỏe" /><View style={styles.list}><Trend label="Giấc ngủ" value="Trung bình 7 giờ 04 phút" detail="Tương tự tuần trước" /><Trend label="Hoạt động" value="4.820 bước / ngày" detail="Chưa đủ dữ liệu để so sánh" /><Trend label="Nhịp tim nghỉ" value="65 bpm" detail="Trong phạm vi ghi nhận gần đây" /></View><Text style={styles.note}>Các xu hướng chỉ hỗ trợ bạn theo dõi sức khỏe, không thay thế tư vấn y tế.</Text></ScrollView></Screen>; }
function Trend({ label, value, detail }: { label: string; value: string; detail: string }) { return <View style={styles.trend}><Text style={styles.trendLabel}>{label}</Text><Text style={styles.trendValue}>{value}</Text><Text style={styles.trendDetail}>{detail}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: space.page, paddingBottom: 36 }, date: { color: palette.muted, fontSize: type.overline, fontWeight: '700', letterSpacing: .7 }, title: { color: palette.ink, fontSize: type.display, fontWeight: '700', letterSpacing: -.8, marginTop: 4 }, intro: { color: palette.muted, fontSize: type.body, lineHeight: 23, marginTop: 10, maxWidth: 350 }, rule: { backgroundColor: palette.line, height: StyleSheet.hairlineWidth, marginVertical: space.xxl }, chartCard: { backgroundColor: palette.sky, borderColor: palette.line, borderRadius: radius.md, borderWidth: 1, padding: space.md }, caption: { borderTopColor: palette.line, borderTopWidth: StyleSheet.hairlineWidth, color: palette.muted, fontSize: 12, lineHeight: 18, marginTop: space.md, paddingTop: space.md }, list: { backgroundColor: palette.lilac, borderColor: palette.line, borderRadius: radius.md, borderWidth: 1 }, trend: { borderBottomColor: palette.line, borderBottomWidth: StyleSheet.hairlineWidth, padding: space.md }, trendLabel: { color: palette.muted, fontSize: 12, fontWeight: '700' }, trendValue: { color: palette.ink, fontSize: 17, fontWeight: '700', marginTop: 6 }, trendDetail: { color: palette.muted, fontSize: 12, marginTop: 4 }, note: { color: palette.muted, fontSize: 11, lineHeight: 16, marginTop: space.md } });
