import React,{useState} from 'react';
import {Link,NavLink,Route,Routes,useNavigate,useParams} from 'react-router-dom';
import {authApi} from './api';

const assessments=[['DASS-21','Đánh giá mức độ trầm cảm, lo âu và căng thẳng','21 câu · 8–10 phút'],['PHQ-9','Sàng lọc mức độ trầm cảm','9 câu · 5 phút'],['GAD-7','Đánh giá mức độ lo âu','7 câu · 3–5 phút']];
const experts=[['TS. Nguyễn Minh Anh','Tâm lý học lâm sàng','4.9','500.000đ'],['ThS. Trần Thu Hà','Tham vấn tâm lý','4.8','450.000đ'],['BS. Lê Hoàng Nam','Tâm thần học','4.9','600.000đ']];
const emotions=[['Hôm nay','Bình yên','Mình đã dành thời gian đi bộ và cảm thấy nhẹ nhõm hơn.','🌿'],['Hôm qua','Vui vẻ','Một cuộc trò chuyện thật tốt với người bạn cũ.','😊'],['18/07/2026','Lo lắng','Có khá nhiều việc cần hoàn thành trong tuần này.','😟']];

function Logo(){return <Link className="logo" to="/"><span className="logo-mark">♥</span><span>MindCare</span></Link>}
function Header(){return <header><Logo/><nav><NavLink to="/">Trang chủ</NavLink><NavLink to="/assessments">Đánh giá tâm lý</NavLink><NavLink to="/diary">Nhật ký cảm xúc</NavLink><NavLink to="/experts">Chuyên gia</NavLink><NavLink to="/ai">AI hỗ trợ</NavLink></nav><div className="header-actions"><button className="icon-btn">☼</button><Link className="text-btn" to="/login">Đăng nhập</Link><Link className="primary small" to="/register">Đăng ký</Link></div></header>}
function Footer(){return <footer><div><b>MindCare</b><p>MindCare. Đồng hành cùng tâm hồn Việt.</p></div><div className="footer-links"><a>Giới thiệu</a><a>Điều khoản sử dụng</a><a>Chính sách bảo mật</a><a>Liên hệ</a></div></footer>}
function Layout({children,plain=false}){return <div className="app">{!plain&&<Header/>}<main className={plain?'auth-main':''}>{children}</main>{!plain&&<Footer/>}</div>}
function Home(){return <Layout><section className="hero"><div><span className="eyebrow">CHĂM SÓC SỨC KHỎE TINH THẦN</span><h1>Lắng nghe tâm trí,<br/><em>chữa lành tâm hồn</em></h1><p>Không ai cần phải đối mặt với những khó khăn một mình. MindCare luôn sẵn sàng đồng hành cùng bạn trên hành trình tìm lại sự cân bằng.</p><div className="row"><Link className="primary" to="/assessments">Bắt đầu đánh giá</Link><Link className="secondary" to="/experts">Tìm chuyên gia</Link></div></div><div className="hero-art"><div className="orb">☁<span>♥</span></div><div className="float-card"><b>Bạn không đơn độc</b><small>Chúng tôi luôn ở đây để lắng nghe</small></div></div></section><section className="section center"><span className="eyebrow">BẮT ĐẦU TỪ ĐÂY</span><h2>Bạn cần hỗ trợ điều gì?</h2><p>Mỗi hành trình đều bắt đầu bằng một bước nhỏ.</p><div className="cards three"><Feature icon="◫" title="Hiểu rõ bản thân" text="Các bài đánh giá khoa học giúp bạn nhận diện trạng thái tinh thần." link="/assessments"/><Feature icon="♡" title="Ghi lại cảm xúc" text="Theo dõi cảm xúc mỗi ngày và nhìn lại hành trình của bạn." link="/diary"/><Feature icon="♙" title="Kết nối chuyên gia" text="Tìm chuyên gia phù hợp và đặt lịch tham vấn riêng tư." link="/experts"/></div></section><section className="cta"><h2>Bạn xứng đáng được lắng nghe</h2><p>Hãy bắt đầu hành trình chăm sóc sức khỏe tinh thần ngay hôm nay.</p><Link className="primary" to="/register">Tham gia MindCare</Link></section></Layout>}
function Feature({icon,title,text,link}){return <Link className="card feature" to={link}><span className="feature-icon">{icon}</span><h3>{title}</h3><p>{text}</p><b>Khám phá →</b></Link>}
function Auth({mode}){const nav=useNavigate();const [error,setError]=useState('');const submit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));try{const res=mode==='login'?await authApi.login(data):await authApi.register(data);if(res?.data?.token||res?.token)localStorage.setItem('mindcare_token',res.data?.token||res.token);nav('/')}catch(ex){setError(ex.message)}};return <Layout plain><div className="auth-side"><Logo/><div><h1>{mode==='login'?'Chào mừng bạn trở lại':'Bắt đầu hành trình chữa lành'}</h1><p>Một không gian an toàn để bạn lắng nghe chính mình và nhận được sự hỗ trợ phù hợp.</p></div><small>© 2026 MindCare</small></div><div className="auth-panel"><form className="auth-card" onSubmit={submit}><h2>{mode==='login'?'Đăng nhập':'Tạo tài khoản'}</h2><p>{mode==='login'?'Tiếp tục hành trình chăm sóc bản thân.':'Chỉ mất một phút để bắt đầu.'}</p>{mode==='register'&&<Field name="fullName" label="Họ và tên" placeholder="Nguyễn Văn A"/>}<Field name="email" label="Email" type="email" placeholder="you@example.com"/><Field name="password" label="Mật khẩu" type="password" placeholder="••••••••"/>{mode==='register'&&<Field name="confirmPassword" label="Xác nhận mật khẩu" type="password" placeholder="••••••••"/>}{error&&<div className="error">{error}</div>}<button className="primary wide">{mode==='login'?'Đăng nhập':'Đăng ký'}</button><div className="divider">hoặc</div><button type="button" className="secondary wide">Tiếp tục với Google</button><p className="switch">{mode==='login'?'Chưa có tài khoản?':'Đã có tài khoản?'} <Link to={mode==='login'?'/register':'/login'}>{mode==='login'?'Đăng ký':'Đăng nhập'}</Link></p></form></div></Layout>}
function Field({label,...props}){return <label className="field"><span>{label}</span><input required {...props}/></label>}
function Assessments(){return <Layout><PageHero eyebrow="ĐÁNH GIÁ TÂM LÝ" title="Hiểu mình hơn, sống nhẹ nhàng hơn" text="Các bài đánh giá được xây dựng dựa trên thang đo khoa học và chỉ mang tính chất tham khảo."/><section className="section"><div className="section-head"><div><h2>Bài đánh giá dành cho bạn</h2><p>Chọn một bài phù hợp với điều bạn đang quan tâm.</p></div><input className="search" placeholder="Tìm bài đánh giá..."/></div><div className="cards three">{assessments.map((a,i)=><article className="card assessment" key={a[0]}><span className={`badge b${i}`}>PHỔ BIẾN</span><div className="test-icon">◎</div><h3>{a[0]}</h3><p>{a[1]}</p><small>{a[2]}</small><Link className="primary wide" to={`/assessment/${i}`}>Bắt đầu đánh giá</Link></article>)}</div></section></Layout>}
function Assessment(){const {id}=useParams();const test=assessments[Number(id)]||assessments[0];const [q,setQ]=useState(1);return <Layout><div className="process"><div className="process-head"><Link to="/assessments">← Thoát</Link><div><b>{test[0]}</b><small>Câu {q} / 9</small></div><span>{Math.round(q/9*100)}%</span></div><div className="progress"><i style={{width:`${q/9*100}%`}}/></div><section className="question-card"><span className="eyebrow">TRONG 2 TUẦN QUA</span><h2>Bạn cảm thấy khó thư giãn hoặc nghỉ ngơi?</h2><div className="answers">{['Không bao giờ','Một vài ngày','Hơn một nửa số ngày','Gần như mỗi ngày'].map(x=><button key={x}>{x}</button>)}</div><div className="question-nav"><button className="secondary" onClick={()=>setQ(Math.max(1,q-1))}>← Trước</button><button className="primary" onClick={()=>setQ(Math.min(9,q+1))}>{q===9?'Xem kết quả':'Tiếp theo →'}</button></div></section></div></Layout>}
function PageHero({eyebrow,title,text}){return <section className="page-hero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></section>}
function Diary(){return <Layout><PageHero eyebrow="NHẬT KÝ CẢM XÚC" title="Hôm nay bạn cảm thấy thế nào?" text="Ghi lại những điều đang diễn ra bên trong bạn, không phán xét, chỉ lắng nghe."/><section className="section diary-grid"><div><div className="section-head"><h2>Nhật ký gần đây</h2><button className="primary">＋ Ghi nhật ký</button></div><div className="timeline">{emotions.map((e,i)=><Link to={`/diary/${i}`} className="diary-card" key={e[0]}><span className="emoji">{e[3]}</span><div><small>{e[0]}</small><h3>{e[1]}</h3><p>{e[2]}</p></div><b>→</b></Link>)}</div></div><aside className="mood-card"><h3>Tổng quan cảm xúc</h3><div className="mood">😊</div><b>Tuần này khá tích cực</b><p>Bạn đã ghi lại cảm xúc 5 ngày liên tiếp.</p><div className="week">T2 T3 T4 T5 T6 T7 CN</div></aside></section></Layout>}
function DiaryDetail(){const {id}=useParams();const e=emotions[Number(id)]||emotions[0];return <Layout><section className="section narrow"><Link to="/diary">← Quay lại nhật ký</Link><article className="journal"><span className="emoji big">{e[3]}</span><span className="eyebrow">{e[0]}</span><h1>{e[1]}</h1><p>{e[2]}</p><hr/><h3>Điều mình biết ơn</h3><p>Một ngày bình thường với những khoảnh khắc nhỏ đáng trân trọng.</p></article></section></Layout>}
function Experts(){return <Layout><PageHero eyebrow="ĐỘI NGŨ CHUYÊN GIA" title="Tìm người đồng hành phù hợp" text="Kết nối với chuyên gia tâm lý được xác minh, an toàn và bảo mật."/><section className="section"><div className="filters"><input className="search" placeholder="Tìm theo tên, chuyên môn..."/><button>Chuyên môn⌄</button><button>Hình thức⌄</button></div><div className="cards three">{experts.map((e,i)=><article className="card expert" key={e[0]}><div className={`avatar a${i}`}>{e[0].split(' ').at(-1)[0]}</div><span className="online">● Đang nhận lịch</span><h3>{e[0]}</h3><p>{e[1]}</p><div className="rating">★ {e[2]} <small>· 120 đánh giá</small></div><b>{e[3]} <small>/ buổi</small></b><Link className="primary wide" to={`/experts/${i}`}>Xem hồ sơ</Link></article>)}</div></section></Layout>}
function ExpertProfile(){const {id}=useParams();const e=experts[Number(id)]||experts[0];return <Layout><section className="section profile-grid"><div><article className="profile-hero"><div className="avatar large">{e[0].at(-1)}</div><div><span className="online">● Đang nhận lịch</span><h1>{e[0]}</h1><p>{e[1]}</p><div className="rating">★ {e[2]} · 120 đánh giá</div></div></article><article className="content-card"><h2>Giới thiệu</h2><p>Tôi tin rằng mỗi người đều có khả năng chữa lành và phát triển khi được lắng nghe trong một không gian an toàn, tôn trọng.</p><h2>Chuyên môn</h2><div className="chips"><span>Lo âu</span><span>Trầm cảm</span><span>Căng thẳng</span><span>Mối quan hệ</span></div></article></div><aside className="booking-card"><h3>Đặt lịch tham vấn</h3><p>Chọn ngày và khung giờ phù hợp</p><div className="calendar-mini">T2　T3　T4　T5　T6<br/><b>20　21　22　23　24</b></div><div className="slots"><button>09:00</button><button>10:30</button><button>14:00</button><button>16:30</button></div><Link className="primary wide" to="/booking">Tiếp tục đặt lịch</Link></aside></section></Layout>}
function Booking(){return <Layout><section className="section narrow"><h1>Xác nhận lịch tham vấn</h1><div className="content-card"><h3>Thông tin buổi tham vấn</h3><p><b>Chuyên gia:</b> TS. Nguyễn Minh Anh</p><p><b>Thời gian:</b> 09:00, Thứ Hai 20/07/2026</p><p><b>Hình thức:</b> Trực tuyến</p><Field label="Lý do tham vấn" placeholder="Chia sẻ ngắn điều bạn muốn được hỗ trợ"/><Link className="primary wide" to="/payment">Tiến hành thanh toán</Link></div></section></Layout>}
function Payment(){return <Layout><section className="section narrow"><h1>Thanh toán</h1><div className="content-card"><h3>Tóm tắt</h3><p>Buổi tham vấn trực tuyến · 60 phút</p><div className="price"><span>Tổng thanh toán</span><b>500.000đ</b></div><h3>Phương thức thanh toán</h3>{['Ví MoMo','VNPay','Thẻ ngân hàng'].map(x=><label className="pay" key={x}><input type="radio" name="pay"/> {x}</label>)}<button className="primary wide">Thanh toán an toàn</button></div></section></Layout>}
function Ai(){const [messages,setMessages]=useState([{by:'ai',text:'Xin chào, mình là MindCare AI. Hôm nay bạn cảm thấy thế nào?'}]);const send=e=>{e.preventDefault();const input=e.currentTarget.elements.message;if(input.value.trim()){setMessages([...messages,{by:'me',text:input.value},{by:'ai',text:'Mình đang lắng nghe. Bạn có thể chia sẻ thêm về điều đó không?'}]);input.value=''}};return <Layout><div className="chat"><aside><h2>AI hỗ trợ</h2><button className="primary wide">＋ Cuộc trò chuyện mới</button><p>Hôm nay</p><b>Chia sẻ cảm xúc</b><small>AI không thay thế chẩn đoán hoặc điều trị chuyên môn.</small></aside><section><div className="chat-head"><div className="bot">✦</div><div><b>MindCare AI</b><small>● Luôn sẵn sàng lắng nghe</small></div></div><div className="messages">{messages.map((m,i)=><div className={`message ${m.by}`} key={i}>{m.text}</div>)}</div><form className="composer" onSubmit={send}><input name="message" placeholder="Chia sẻ điều bạn đang nghĩ..."/><button className="primary">Gửi ↑</button></form></section></div></Layout>}
function Profile(){return <Layout><section className="section"><div className="profile-banner"><div className="avatar large">A</div><div><h1>Nguyễn Minh Anh</h1><p>minhanh@example.com</p></div><button className="secondary">Chỉnh sửa hồ sơ</button></div><div className="settings-grid"><aside className="side-tabs"><NavLink to="/profile">Thông tin cá nhân</NavLink><NavLink to="/bookmarks">Đã lưu</NavLink><NavLink to="/settings">Cài đặt</NavLink></aside><div className="content-card"><h2>Thông tin cá nhân</h2><div className="form-grid"><Field label="Họ và tên" defaultValue="Nguyễn Minh Anh"/><Field label="Số điện thoại" defaultValue="090 123 4567"/><Field label="Ngày sinh" type="date"/><Field label="Giới tính" defaultValue="Nữ"/></div><button className="primary">Lưu thay đổi</button></div></div></section></Layout>}
function Bookmarks(){return <Layout><section className="section"><h1>Nội dung đã lưu</h1><div className="cards three">{experts.slice(0,2).map(e=><article className="card" key={e[0]}><h3>{e[0]}</h3><p>{e[1]}</p><Link to="/experts/0">Xem hồ sơ →</Link></article>)}{assessments.slice(0,1).map(e=><article className="card" key={e[0]}><h3>{e[0]}</h3><p>{e[1]}</p><Link to="/assessment/0">Làm bài →</Link></article>)}</div></section></Layout>}
function Settings(){return <Layout><section className="section"><h1>Cài đặt hệ thống</h1><p>Quản lý tài khoản và tùy chỉnh trải nghiệm MindCare của bạn.</p><div className="content-card settings"><h2>🔔 Thông báo</h2><Toggle label="Nhắc lịch tham vấn"/><Toggle label="Nhật ký cảm xúc hằng ngày"/><h2>🔒 Bảo mật</h2><button className="setting-row">Thay đổi mật khẩu <b>›</b></button><h2>◎ Ngôn ngữ</h2><label className="pay"><input type="radio" defaultChecked/> Tiếng Việt</label><label className="pay"><input type="radio"/> English (US)</label></div></section></Layout>}
function Toggle({label}){return <label className="setting-row"><span>{label}</span><input type="checkbox" defaultChecked/></label>}
function NotFound(){return <Layout><section className="section center"><h1>Không tìm thấy trang</h1><Link className="primary" to="/">Về trang chủ</Link></section></Layout>}
export default function App(){return <Routes><Route path="/" element={<Home/>}/><Route path="/login" element={<Auth mode="login"/>}/><Route path="/register" element={<Auth mode="register"/>}/><Route path="/assessments" element={<Assessments/>}/><Route path="/assessment/:id" element={<Assessment/>}/><Route path="/diary" element={<Diary/>}/><Route path="/diary/:id" element={<DiaryDetail/>}/><Route path="/experts" element={<Experts/>}/><Route path="/experts/:id" element={<ExpertProfile/>}/><Route path="/booking" element={<Booking/>}/><Route path="/payment" element={<Payment/>}/><Route path="/ai" element={<Ai/>}/><Route path="/profile" element={<Profile/>}/><Route path="/bookmarks" element={<Bookmarks/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<NotFound/>}/></Routes>}
