import { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { AppScreen } from '@/components/app-screen'; import { ScreenHeader } from '@/components/screen-header';
import { useAuth } from '@/features/auth/auth-context'; import { colors, fonts, radius, spacing, type } from '@/theme/tokens';
import { reminderService, type Reminder } from './reminder.service';
import { ensurePushRegistered } from '@/features/notifications/push-registration';
const labels = { DAILY_CHECK_IN: ['Check-in cảm xúc', 'Một lời nhắc nhẹ để ghi nhận cảm xúc trong ngày.'], SELF_CARE: ['Tự chăm sóc', 'Nhắc bạn dành thời gian cho kế hoạch của mình.'] } as const; const times = ['08:00', '12:00', '20:00'];
export function ReminderScreen() { const { session } = useAuth(); const [items, setItems] = useState<Reminder[]>([]); const [error, setError] = useState(false);
  const load = useCallback(async () => { if (!session?.accessToken) return; try { setItems(await reminderService.list(session.accessToken)); setError(false); } catch { setError(true); } }, [session?.accessToken]); useEffect(() => { void load(); }, [load]);
  async function save(item: Reminder) { if (!session?.accessToken) return; setItems((values) => values.map((value) => value.id === item.id ? item : value)); try { if (item.enabled) await ensurePushRegistered(session.accessToken); await reminderService.update(session.accessToken, item); } catch { setError(true); void load(); } }
  return <AppScreen><ScreenHeader title="Nhắc nhở" /><ScrollView contentContainerStyle={styles.content}><Text style={styles.intro}>Bạn quyết định khi nào MindCare được nhắc. Có thể tắt bất kỳ lúc nào.</Text>{error && <Text style={styles.error}>Không thể đồng bộ lịch nhắc. Hãy thử lại.</Text>}{items.map((item) => <View style={styles.card} key={item.id}><View style={styles.row}><View style={styles.flex}><Text style={styles.title}>{labels[item.reminderType][0]}</Text><Text style={styles.body}>{labels[item.reminderType][1]}</Text></View><Switch value={item.enabled} onValueChange={(enabled) => void save({ ...item, enabled })} trackColor={{ false: colors.lineStrong, true: colors.brand }} /></View><Text style={styles.label}>Thời điểm</Text><View style={styles.times}>{times.map((time) => <Pressable disabled={!item.enabled} onPress={() => void save({ ...item, localTime: time })} key={time} style={[styles.time, item.localTime.startsWith(time) && styles.timeActive, !item.enabled && styles.disabled]}><Text style={[styles.timeText, item.localTime.startsWith(time) && styles.timeTextActive]}>{time}</Text></Pressable>)}</View></View>)}</ScrollView></AppScreen>; }
const styles = StyleSheet.create({ content: { padding: spacing.page, gap: spacing.md }, intro: { color: colors.muted, fontFamily: fonts.regular, fontSize: type.body, lineHeight: 23 }, error: { color: colors.danger, fontFamily: fonts.medium, fontSize: type.label }, card: { backgroundColor: colors.surface, borderColor: colors.line, borderWidth: 1, borderRadius: radius.card, padding: spacing.md, gap: spacing.md }, row: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, flex: { flex: 1 }, title: { color: colors.ink, fontFamily: fonts.bold, fontSize: type.cardTitle }, body: { color: colors.muted, fontFamily: fonts.regular, fontSize: type.label, lineHeight: 20, marginTop: spacing.xxs }, label: { color: colors.inkSoft, fontFamily: fonts.semibold, fontSize: type.label }, times: { flexDirection: 'row', gap: spacing.xs }, time: { borderColor: colors.lineStrong, borderWidth: 1, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: spacing.xs }, timeActive: { backgroundColor: colors.brand, borderColor: colors.brand }, disabled: { opacity: 0.45 }, timeText: { color: colors.inkSoft, fontFamily: fonts.medium, fontSize: type.label }, timeTextActive: { color: colors.accentInk } });
