import { useLocalSearchParams, useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { DetailScreen, PrimaryAction, Surface } from '../../src/components/secondary-ui';
import { palette, radius, space, type } from '../../src/theme/tokens';
const prompts: Record<string, { title: string; question: string }> = { 'phq-9': { title: 'Sàng lọc trầm cảm', question: 'Trong hai tuần qua, bạn có thấy ít hứng thú hoặc ít niềm vui khi làm mọi việc không?' }, 'gad-7': { title: 'Sàng lọc lo âu', question: 'Trong hai tuần qua, bạn có cảm thấy căng thẳng, lo lắng hoặc bồn chồn không?' }, stress: { title: 'Mức căng thẳng', question: 'Trong tuần vừa qua, bạn có thấy khó kiểm soát những điều quan trọng trong cuộc sống không?' } };
const answers = ['Không hề', 'Vài ngày', 'Hơn nửa số ngày', 'Gần như mỗi ngày'];
export default function AssessmentProcessScreen() { const { code } = useLocalSearchParams<{ code: string }>(); const router = useRouter(); const item = useMemo(() => prompts[code ?? ''] ?? prompts.stress, [code]); const [selected, setSelected] = useState<number | null>(null); const [finished, setFinished] = useState(false); return <DetailScreen title="Đánh giá"><Text style={styles.count}>CÂU 1 / 7</Text><Text style={styles.title}>{item.title}</Text><Text style={styles.question}>{item.question}</Text><Surface>{answers.map((answer, index) => <Pressable key={answer} onPress={() => setSelected(index)} style={[styles.answer, index < answers.length - 1 && styles.answerRule, selected === index && styles.answerSelected]}><View style={[styles.radio, selected === index && styles.radioSelected]}>{selected === index ? <View style={styles.dot} /> : null}</View><Text style={styles.answerText}>{answer}</Text></Pressable>)}</Surface>{finished ? <View style={styles.result}><Text style={styles.resultTitle}>Đã lưu câu trả lời mẫu</Text><Text style={styles.resultText}>Đây là prototype UI; không có kết quả hay dữ liệu nào được lưu.</Text></View> : <PrimaryAction label="Tiếp tục" icon="arrow-forward" onPress={() => selected !== null && setFinished(true)} />}{finished ? <PrimaryAction label="Quay lại danh sách" onPress={() => router.back()} /> : null}</DetailScreen>; }
const styles = StyleSheet.create({ count: { color: palette.primary, fontSize: type.overline, fontWeight: '800', letterSpacing: .8, marginTop: space.md }, title: { color: palette.ink, fontSize: type.title, fontWeight: '700', marginTop: 5 }, question: { color: palette.ink, fontSize: 18, fontWeight: '600', lineHeight: 27, marginBottom: space.xl, marginTop: space.md }, answer: { alignItems: 'center', flexDirection: 'row', gap: space.sm, minHeight: 62, paddingHorizontal: space.md }, answerRule: { borderBottomColor: palette.line, borderBottomWidth: StyleSheet.hairlineWidth }, answerSelected: { backgroundColor: palette.emotionSelected }, radio: { alignItems: 'center', borderColor: palette.chartMuted, borderRadius: 10, borderWidth: 1, height: 20, justifyContent: 'center', width: 20 }, radioSelected: { borderColor: palette.primary }, dot: { backgroundColor: palette.primary, borderRadius: 5, height: 10, width: 10 }, answerText: { color: palette.ink, flex: 1, fontSize: type.label }, result: { backgroundColor: palette.mint, borderColor: palette.line, borderRadius: radius.md, borderWidth: 1, marginBottom: space.md, padding: space.md }, resultTitle: { color: palette.ink, fontSize: type.label, fontWeight: '700' }, resultText: { color: palette.muted, fontSize: 13, lineHeight: 19, marginTop: 4 } });
