import Ionicons from '@expo/vector-icons/Ionicons';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { BackButton, Screen, SoftButton } from '../../src/components/ui';
import { palette, space, type } from '../../src/theme/tokens';
const steps = [{ name: 'Hít vào', guide: 'Hít vào tự nhiên trong 4 nhịp.' }, { name: 'Giữ lại', guide: 'Dừng lại nếu bạn thấy không thoải mái.' }, { name: 'Thở ra', guide: 'Thở ra chậm hơn một chút, trong 6 nhịp.' }];
export default function RitualScreen() { const router = useRouter(); const [step, setStep] = useState(0); const current = steps[step]; const next = () => step === steps.length - 1 ? router.back() : setStep(step + 1); return <Screen style={styles.screen}><View style={styles.header}><BackButton onPress={() => router.back()} /><Text style={styles.headerTitle}>Hướng dẫn thở</Text><View style={{ width: 44 }} /></View><View style={styles.body}><Text style={styles.kicker}>BÀI THỰC HÀNH NGẮN</Text><Text style={styles.title}>Tạm dừng trong một phút.</Text><View style={styles.timer}><Text style={styles.timerNumber}>0{step + 1}</Text><Text style={styles.timerLabel}>/ 03</Text></View><View style={styles.divider} /><Text style={styles.step}>{current.name}</Text><Text style={styles.guide}>{current.guide}</Text><View style={styles.progress}>{steps.map((_, index) => <View key={index} style={[styles.progressLine, index <= step && styles.progressActive]} />)}</View><SoftButton label={step === 2 ? 'Kết thúc' : 'Tiếp tục'} icon="arrow-forward" onPress={next} filled /></View><Text style={styles.footer}>Bạn có thể dừng bất cứ lúc nào.</Text></Screen>; }
const styles = StyleSheet.create({ screen: { justifyContent: 'space-between' }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingHorizontal: space.page, paddingTop: space.xs }, headerTitle: { color: palette.ink, fontSize: type.label, fontWeight: '700' }, body: { alignItems: 'flex-start', gap: space.lg, paddingHorizontal: 36 }, kicker: { color: palette.muted, fontSize: type.overline, fontWeight: '700', letterSpacing: .7 }, title: { color: palette.ink, fontSize: 28, fontWeight: '700', letterSpacing: -.7, lineHeight: 35 }, timer: { alignItems: 'baseline', flexDirection: 'row', marginTop: space.xl }, timerNumber: { color: palette.primary, fontSize: 72, fontWeight: '300', letterSpacing: -3 }, timerLabel: { color: palette.muted, fontSize: 18, marginLeft: 8 }, divider: { backgroundColor: palette.line, height: StyleSheet.hairlineWidth, width: '100%' }, step: { color: palette.ink, fontSize: 21, fontWeight: '700' }, guide: { color: palette.muted, fontSize: type.body, lineHeight: 24, maxWidth: 290 }, progress: { flexDirection: 'row', gap: 6, width: '100%' }, progressLine: { backgroundColor: palette.line, height: 3, width: 44 }, progressActive: { backgroundColor: palette.primary }, footer: { color: palette.muted, fontSize: 12, paddingBottom: space.xl, textAlign: 'center' } });
