package com.mindcare.emotionservice.assessment.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Null;
import jakarta.validation.constraints.PositiveOrZero;
import jakarta.validation.constraints.Size;

public record UpsertQuestionRequest(
        @NotBlank
        @Size(max = 5_000)
        String questionText,
        @NotNull
        @PositiveOrZero
        Integer orderIndex,
        @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
        @Null(message = "answerOptions are generated by the server and must be omitted")
        Object answerOptions
) {
    public UpsertQuestionRequest(String questionText, Integer orderIndex) {
        this(questionText, orderIndex, null);
    }
}
