/* Hallmark · genre: modern-minimal · macrostructure: Native Content Flow · design-system: design.md · designed-as-app */
import Ionicons from '@expo/vector-icons/Ionicons';
import { useRouter } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { ActionButton } from '@/components/buttons';
import { AppScreen } from '@/components/app-screen';
import { SectionHeader } from '@/components/section-header';
import { emotionOptionMap } from '@/features/emotion/emotion.constants';
import { EmotionFaceIcon } from '@/features/emotion/emotion-face';
import { EmotionPicker } from '@/features/emotion/emotion-picker';
import { EmotionTrendChart, EmotionTrendSkeleton } from '@/features/emotion/emotion-trend-chart';
import type { EmotionJournal, EmotionLevel } from '@/features/emotion/emotion.types';
import { useEmotionJournal } from '@/features/emotion/use-emotion-journal';
import { emotionService } from '@/services/emotion/emotion.service';
import { colors, fonts, radius, spacing, type } from '@/theme/tokens';

export default function JournalScreen() {
  const router = useRouter();
  const { entries, trends, loading, refreshing, error, reload, token } = useEmotionJournal();
  const [emotion, setEmotion] = useState<EmotionLevel>();
  const [note, setNote] = useState('');
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState('');
  const [saved, setSaved] = useState(false);
  const checkInsThisWeek = useMemo(() => trends.reduce((total, point) => total + point.count, 0), [trends]);
  const save = async () => {
    if (!token || !emotion || saving) return;
    setSaving(true); setSaveError(''); setSaved(false);
    try { await emotionService.create(token, { emotionType: emotion, content: note.trim() }); setEmotion(undefined); setNote(''); setSaved(true); await reload(true); }
    catch (caught) { setSaveError(caught instanceof Error ? caught.message : 'Không thể lưu nhật ký. Vui lòng thử lại.'); }
    finally { setSaving(false); }
  };
  return <AppScreen><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl colors={[colors.brand]} onRefresh={() => void reload(true)} refreshing={refreshing} tintColor={colors.brand} />} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={styles.date}>{new Intl.DateTimeFormat('vi-VN', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date()).toLocaleUpperCase('vi-VN')}</Text><Text accessibilityRole="header" style={styles.title}>Hôm nay</Text></View><Pressable accessibilityLabel="Dữ liệu sức khỏe" accessibilityRole="button" onPress={() => router.push('/(tabs)/health-connect')} style={({ pressed }) => [styles.iconButton, pressed && styles.pressed]}><Ionicons color={colors.ink} name="fitness-outline" size={21} /></Pressable></View>
    <View style={styles.statusLine}><View style={styles.statusDot} /><View style={styles.statusCopy}><Text style={styles.statusTitle}>{loading ? 'Đang cập nhật nhật ký của bạn' : 'Nhật ký cảm xúc đã sẵn sàng'}</Text><Text style={styles.statusText}>{error ? 'Kéo xuống để thử tải lại dữ liệu.' : 'Ghi một check-in ngắn để theo dõi thay đổi theo thời gian.'}</Text></View></View>
    <SectionHeader title="Bạn đang cảm thấy thế nào?" />
    <View style={styles.moodPanel}><EmotionPicker disabled={saving} onChange={(value) => { setEmotion(value); setSaved(false); }} value={emotion} /><Text style={styles.inputLabel}>Điều gì đang ở trong tâm trí bạn?</Text><TextInput accessibilityLabel="Viết thêm về ngày hôm nay" maxLength={5000} multiline onChangeText={(value) => { setNote(value); setSaved(false); }} placeholder="Viết một vài dòng nếu bạn muốn…" placeholderTextColor={colors.muted} style={styles.noteInput} textAlignVertical="top" value={note} /><View style={styles.formMeta}><Text style={styles.counter}>{note.length}/5000</Text>{saved ? <Text accessibilityLiveRegion="polite" style={styles.savedText}>Đã lưu nhật ký</Text> : null}</View>{saveError ? <Text accessibilityRole="alert" style={styles.errorText}>{saveError}</Text> : null}<View style={styles.formActions}><ActionButton disabled={saving || (!emotion && !note)} label="Xóa" onPress={() => { setEmotion(undefined); setNote(''); setSaveError(''); }} style={styles.formButton} tone="secondary" /><ActionButton disabled={!emotion || saving} label={saveError ? 'Thử lại' : 'Lưu check-in'} loading={saving} onPress={() => void save()} style={styles.formButton} /></View><Text style={styles.moodNote}>Check-in này chỉ dành cho bạn và giúp bạn nhìn lại xu hướng cảm xúc theo thời gian.</Text></View>
    <View style={styles.rule} /><SectionHeader actionLabel="Xem lịch" onAction={() => router.push('/(tabs)/journal-history')} title="Cảm xúc gần đây" /><View style={styles.chartCard}>{loading ? <EmotionTrendSkeleton /> : error ? <Text style={styles.errorText}>{error}</Text> : <EmotionTrendChart points={trends} />}<Text style={styles.caption}>{checkInsThisWeek ? `${checkInsThisWeek} check-in trong 7 ngày gần đây.` : 'Chưa có check-in nào trong 7 ngày gần đây.'}</Text></View>
    <View style={styles.rule} /><SectionHeader title="Một việc đơn giản tiếp theo" /><View style={styles.recommendation}><View style={styles.recommendationIcon}><Ionicons color={colors.brand} name="walk-outline" size={21} /></View><View style={styles.recommendationBody}><Text style={styles.recommendationTitle}>Dành 10 phút cho bản thân</Text><Text style={styles.recommendationText}>Một hoạt động nhẹ nhàng có thể giúp bạn tạm dừng và lắng nghe cơ thể.</Text><Pressable accessibilityRole="button" onPress={() => router.push('/(tabs)/progress')} style={({ pressed }) => [styles.softAction, pressed && styles.pressed]}><Text style={styles.softActionText}>Xem tiến trình</Text><Ionicons color={colors.brand} name="arrow-forward" size={17} /></Pressable></View></View>
    {entries.length ? <><View style={styles.rule} /><SectionHeader actionLabel="Xem tất cả" onAction={() => router.push('/(tabs)/journal-history')} title="Nhật ký gần đây" /><View style={styles.recent}>{entries.slice(0, 3).map((entry, index) => <JournalRow entry={entry} key={entry.id} last={index === Math.min(entries.length, 3) - 1} />)}</View></> : null}
  </ScrollView></AppScreen>;
}

function JournalRow({ entry, last }: { entry: EmotionJournal; last: boolean }) { const option = emotionOptionMap[entry.emotionType]; return <View style={[styles.journalRow, !last && styles.journalRowRule]}><EmotionFaceIcon color={option.color} face={option.face} size={36} /><View style={styles.journalCopy}><Text style={styles.journalTitle}>{option.label}</Text><Text numberOfLines={2} style={styles.journalNote}>{entry.content || 'Không có ghi chú'}</Text></View><Text style={styles.journalDate}>{new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: '2-digit' }).format(new Date(entry.createdAt))}</Text></View>; }

export function JournalCard({ item }: { item: EmotionJournal }) { return <JournalRow entry={item} last />; }

const styles = StyleSheet.create({
  content: { padding: spacing.page, paddingBottom: 40 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.lg }, date: { color: colors.muted, fontFamily: fonts.semibold, fontSize: type.caption, letterSpacing: .7 }, title: { color: colors.ink, fontFamily: fonts.bold, fontSize: type.title, letterSpacing: -.8, lineHeight: 38, marginTop: spacing.xxs }, iconButton: { alignItems: 'center', borderColor: colors.line, borderRadius: radius.sm, borderWidth: StyleSheet.hairlineWidth, height: 44, justifyContent: 'center', width: 44 },
  statusLine: { alignItems: 'flex-start', backgroundColor: colors.mint, borderLeftColor: colors.brand, borderLeftWidth: 3, flexDirection: 'row', gap: spacing.xs, marginBottom: spacing.xl, padding: spacing.md }, statusDot: { backgroundColor: colors.brand, borderRadius: 4, height: 8, marginTop: 5, width: 8 }, statusCopy: { flex: 1 }, statusTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: type.label }, statusText: { color: colors.muted, fontFamily: fonts.regular, fontSize: type.caption, lineHeight: 18, marginTop: 3 },
  moodPanel: { backgroundColor: colors.brandSoft, borderColor: colors.line, borderRadius: radius.card, borderWidth: 1, marginTop: spacing.md, padding: spacing.md }, inputLabel: { color: colors.ink, fontFamily: fonts.medium, fontSize: type.label, marginBottom: spacing.xs, marginTop: spacing.lg }, noteInput: { backgroundColor: colors.surface, borderColor: colors.line, borderRadius: radius.sm, borderWidth: 1, color: colors.ink, fontFamily: fonts.regular, fontSize: type.body, lineHeight: 22, minHeight: 96, padding: spacing.sm }, formMeta: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', minHeight: 28 }, counter: { color: colors.muted, fontFamily: fonts.regular, fontSize: type.caption }, savedText: { color: colors.mintInk, fontFamily: fonts.medium, fontSize: type.caption }, errorText: { color: colors.danger, fontFamily: fonts.regular, fontSize: type.caption, lineHeight: 18, marginTop: spacing.xs }, formActions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.xs }, formButton: { flex: 1 }, moodNote: { borderTopColor: colors.line, borderTopWidth: StyleSheet.hairlineWidth, color: colors.muted, fontFamily: fonts.regular, fontSize: type.caption, lineHeight: 18, marginTop: spacing.md, paddingTop: spacing.md },
  rule: { backgroundColor: colors.line, height: StyleSheet.hairlineWidth, marginVertical: spacing.xl }, chartCard: { backgroundColor: colors.surfaceMuted, borderColor: colors.line, borderRadius: radius.card, borderWidth: 1, marginTop: spacing.md, padding: spacing.md }, caption: { borderTopColor: colors.line, borderTopWidth: StyleSheet.hairlineWidth, color: colors.muted, fontFamily: fonts.regular, fontSize: type.caption, lineHeight: 18, marginTop: spacing.md, paddingTop: spacing.md },
  recommendation: { alignItems: 'flex-start', backgroundColor: colors.warningSoft, borderColor: colors.line, borderLeftColor: colors.warning, borderLeftWidth: 3, borderRadius: radius.card, borderWidth: 1, flexDirection: 'row', gap: spacing.md, marginTop: spacing.md, padding: spacing.md }, recommendationIcon: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: radius.sm, height: 42, justifyContent: 'center', width: 42 }, recommendationBody: { flex: 1, gap: 7 }, recommendationTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: type.body }, recommendationText: { color: colors.muted, fontFamily: fonts.regular, fontSize: type.label, lineHeight: 19 }, softAction: { alignItems: 'center', alignSelf: 'flex-start', borderColor: colors.brand, borderRadius: radius.sm, borderWidth: 1, flexDirection: 'row', gap: 7, minHeight: 44, paddingHorizontal: spacing.sm }, softActionText: { color: colors.brand, fontFamily: fonts.semibold, fontSize: type.label },
  recent: { backgroundColor: colors.surfaceMuted, borderColor: colors.line, borderRadius: radius.card, borderWidth: 1, marginTop: spacing.md, overflow: 'hidden' }, journalRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, minHeight: 76, paddingHorizontal: spacing.md }, journalRowRule: { borderBottomColor: colors.line, borderBottomWidth: StyleSheet.hairlineWidth }, journalCopy: { flex: 1, minWidth: 0 }, journalTitle: { color: colors.ink, fontFamily: fonts.semibold, fontSize: type.label }, journalNote: { color: colors.muted, fontFamily: fonts.regular, fontSize: type.caption, marginTop: 3 }, journalDate: { color: colors.muted, fontFamily: fonts.regular, fontSize: type.caption }, pressed: { opacity: .72, transform: [{ translateY: 1 }] },
});
